name: Python CI

on:
    push:
        branches:
            - main
    pull_request:
        branches: 
            - main
jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10.12"
                  check-latest: false

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              run: pytest
